# Default values for dti-test.
# Declare variables to be passed into your templates.
fullnameOverride: dti-test
replicaCount: 1
image:
  repository: dti-test
  tag: #{Build.BuildId}#
  pullPolicy: IfNotPresent
  imagePullSecretName: acr-private-secret
imagePullSecrets: []
service:
  type: ClusterIP
  port: 80

probes:
  enabled: false

ingress:
  enabled: true
  whitelist:
    ranges:
  annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
  hostName: hostName
  tls:
    secretName: secretName
secrets: {}
resources:
  limits:
    cpu: cpuLimit
    memory: memoryLimit
  requests:
    cpu: cpuRequests
    memory: memoryRequests
nodeSelector: {}

tolerations: []

affinity: {}

environment: 
  stage: staging

appSettings:
  configMap: dti-test
  path: /app/appsettings.json
  subPath: appsettings.json

autoscale:
  minReplicas: minReplicas
  maxReplicas: maxReplicas
  averageCPUUtilization: averageCpuUtilization

team: dti

annotations: {}
