FROM mcr.microsoft.com/dotnet/core/sdk:3.0
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80

WORKDIR /src
COPY ["Dti.Api.Test.Facades/Dti.Api.Test.Facades.csproj", "Dti.Api.Test.Facades/"]
COPY ["Dti.Api.Test.Models/Dti.Api.Test.Models.csproj", "Dti.Api.Test.Models/"]
COPY ["Dti.Api.Test.Services/Dti.Api.Test.Services.csproj", "Dti.Api.Test.Services/"]
COPY ["Dti.Api.Test/Dti.Api.Test.csproj", "Dti.Api.Test/"]

RUN dotnet restore "Dti.Api.Test/Dti.Api.Test.csproj"
COPY . .
WORKDIR "/src/Dti.Api.Test"
RUN dotnet build --no-restore "Dti.Api.Test.csproj" -c $BUILD_CONFIGURATION

RUN echo "exec dotnet run --no-build --no-launch-profile -c $BUILD_CONFIGURATION --" > /entrypoint.sh

ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]